/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../../../tools/AndroidStudio3.2/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
/* Header for class jan_jason_ndkdemo_NdkDemoActivity */

#ifndef _Included_jan_jason_ndkdemo_NdkDemoActivity
#define _Included_jan_jason_ndkdemo_NdkDemoActivity


#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     jan_jason_ndkdemo_NdkDemoActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jan_jason_ndkdemo_NdkDemoActivity_stringFromJNI
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif


#endif

